name: Develop CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER_DEV }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD_DEV }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: 
          - 5432:5432
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL_DEV }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Run install dependencies
        run: npm install

      - name: Run build application
        run: npm run build

      - name: Start migration
        run: npx prisma migrate deploy

      - name: Run unit Tests
        run: npm run test

      - name: Run Coverage Tests
        run: npm run test:cov

      - name: Run E2E Tests
        run: npm run test:e2e
      
      - name: Run Coverage E2E Tests
        run: npm run test:e2e:cov